### ISSUE TITLE
Missing jsonref and jsonschema python packages

### ISSUE THREAD

**Issue by wonder-sk** [tudelft3d/cityjson-qgis-plugin#4]
Trying to run the plugin on Ubuntu 18.04 I get this:

```
Couldn't load plugin 'CityJSON-loader' due to an error when calling its classFactory() method 

ModuleNotFoundError: No module named 'jsonref' 
```

jsonref module is not even in ubuntu/debian package repository, I had to use `python3 -m pip install jsonref`

On the next start, there was another missing package:
```ModuleNotFoundError: No module named 'jsonschema' ```

This one is available in ubuntu/debian as `python3-jsonschema` package.

Maybe it would be good to ship these python packages with the plugin as they are not automatically installed and users may have troubles installing those manually...

**Comment by liberostelios** [comment]
Thank you for noticing.

Fixed by removing the `jsonref` and `jsonschema` on 25a32d26e5abecefb0794385f037d614ef726b56.
