### ISSUE TITLE
Plugin .zip package contains __MACOSX

### ISSUE THREAD

**Issue by wonder-sk** [tudelft3d/cityjson-qgis-plugin#6]
The package contains __MACOSX directory, so after installing the plugin I get `__MACOSX` listed as a broken plugin

![image](https://user-images.githubusercontent.com/193367/46106526-3bcaa380-c1d9-11e8-9c8c-6a1cd6471350.png)

**Comment by liberostelios** [comment]
I am sorry for the inconvenience.

Fixed in version 0.1.1.
