### ISSUE TITLE
Create layer group instead of prefix

### ISSUE THREAD

**Issue by balazsdukai** [tudelft3d/cityjson-qgis-plugin#9]
I think it would be more convenient to have a layer group instead of prefixing the layers with the file name when the "Split by object type" option is checked. It makes it easier to manage the layers when there are layers from other sources as well in the project.

![image](https://user-images.githubusercontent.com/7190603/60462402-791cff80-9c49-11e9-931f-077e208ceee8.png)

**Comment by liberostelios** [comment]
Fixed in 6451c07fe6f0cc325cb8b06d7ae5bb8ad2c68ceb
